apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: mammoth-search-watch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mammoth-data
  namespace: mammoth-search-watch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
