apiVersion: v1
kind: Secret
metadata:
  name: search-watch-secret
  namespace: mammoth-search-watch
type: Opaque
stringData:
  DATABASE_URL: postgres://mammoth_search_watch:mammoth_search_watch_password@postgres:5432/search_watch
  POSTGRES_PASSWORD: mammoth_search_watch_password
  MAMMOTH_POSTGRES_PASSWORD: mammoth_search_watch_password
